# Scarlett Karaoke API - Cloudflare Worker Configuration

name = "scarlett-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

# Database binding for local development
[[d1_databases]]
binding = "DB"
database_name = "scarlett-dev"
database_id = "c0cebf07-8c3b-4c03-9ecd-589d9a8346e6"

# Environment variables
[env.development.vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

# Database binding
[[env.development.d1_databases]]
binding = "DB"
database_name = "scarlett-dev"
database_id = "c0cebf07-8c3b-4c03-9ecd-589d9a8346e6"

[[env.production.d1_databases]]
binding = "DB"
database_name = "scarlett-prod"
database_id = "c0cebf07-8c3b-4c03-9ecd-589d9a8346e6"

# Secrets (set via wrangler secret put)
# JWT_SECRET - Your JWT signing secret
# GENIUS_API_KEY - Your Genius API key (optional)
# ELEVENLABS_API_KEY - Your ElevenLabs API key (optional, fallback for STT)
# DEEPGRAM_API_KEY - Your Deepgram API key (primary STT provider)

# KV bindings (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Custom domains (set these up in Cloudflare dashboard)
# [env.production]
# routes = [
#   { pattern = "api.scarlett.dev/*", zone_name = "scarlett.dev" }
# ] 