name: Main CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest  # blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.45
          
      - name: Cache dependencies
        uses: actions/cache@v4  # useblacksmith/cache@v5
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: deps-${{ hashFiles('**/bun.lock', '**/package.json') }}
          
      - name: Install dependencies
        run: bun install
        
      - name: Lint
        run: bun run lint
        
      - name: Type check
        run: bun run type-check
        
      - name: Test
        run: bun run test

  storybook-build:
    runs-on: ubuntu-latest  # blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.45
          
      - name: Cache dependencies
        uses: actions/cache@v4  # useblacksmith/cache@v5
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: deps-${{ hashFiles('**/bun.lock', '**/package.json') }}
          
      - name: Install dependencies
        run: bun install
        
      - name: Build Storybook
        run: bun run build-storybook
        
      - name: Upload Storybook artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: packages/ui/storybook-static

  chromatic-tests:
    runs-on: ubuntu-latest  # blacksmith-2vcpu-ubuntu-2204
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Chromatic
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.45
          
      - name: Cache dependencies
        uses: actions/cache@v4  # useblacksmith/cache@v5
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: deps-${{ hashFiles('**/bun.lock', '**/package.json') }}
          
      - name: Install dependencies
        run: bun install
        
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          workingDir: packages/ui

  build-apps:
    runs-on: ubuntu-latest  # blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.45
          
      - name: Cache dependencies
        uses: actions/cache@v4  # useblacksmith/cache@v5
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: deps-${{ hashFiles('**/bun.lock', '**/package.json') }}
          
      - name: Install dependencies
        run: bun install
        
      - name: Build all apps
        run: bun run build